const A='assets/';
const screen=document.getElementById('screen');
const dock=document.getElementById('dock');

// V15.3 opening identity: the app starts with the family welcome, then enters the app.
window.addEventListener('load',()=>{
  const splash=document.getElementById('appSplash');
  if(!splash) return;
  setTimeout(()=>splash.classList.add('splash-hide'),3200);
  setTimeout(()=>splash.remove(),4000);
});
const nav=[
 ['bluetooth','bluetooth.png','بلوتوث'],['usb','usb.png','گنجینه'],['music','music.png','آوای نوا'],['rgb','rgb.png','RGB'],['galaxy','galaxy.png','کهکشانی'],['ai','ai.png','نورا'],['control','control.png','اتاق فرمان']
];

/* =========================================================
   KOROSH NOVA — DATA-DRIVEN SECRET ROOM
   Visual assets are references, never embedded in code.
   Future GitHub asset additions belong in:
   assets/secret_room/manifest.json
   so the UI logic does not need to be rewritten.
   ========================================================= */
const secretConfig={
 defaults:{
  chest:'secret_room/chest_zohreh.png',
  background:'page_skins/galaxy_background_clean.jpg',
  frame:'page_frames/frame_gold_floral.png',
  familyPhoto:'secret_room/family_selected.jpg',
  albumBackground:'page_skins/galaxy_background_clean.jpg',
  albumFrame:'page_frames/frame_cosmic_spiral.png',
  theme:'classic',
  effect:'نور آرام'
 },
 gifts:{
  chest:[
   ['صندوق نور','secret_room/chest_zohreh.png'],['صندوق مهر','secret_room/chest_mother.png'],['صندوق خاطره','secret_room/chest_hosein.png'],['صندوق شادی','secret_room/chest_zeynab.png'],['صندوق پدر','secret_room/chest_father.png'],['صندوق خانواده','secret_room/chest_family.png']
  ],
  background:[
   ['کهکشان نوا','page_skins/galaxy_background_clean.jpg'],['کنترل نوا','page_skins/control_background.jpg'],['کنترل روشن','page_skins/control_background_bright.jpg']
  ],
  frame:[
   ['کریستال رنگین','page_frames/frame_rainbow_crystal.png'],['طلایی گل‌دار','page_frames/frame_gold_floral.png'],['مارپیچ کیهانی','page_frames/frame_cosmic_spiral.png']
  ],
  familyPhoto:[['عکس نمونه خانواده','secret_room/family_selected.jpg']],
  albumBackground:[['کهکشان خاطره','page_skins/galaxy_background_clean.jpg'],['کنترل نوا','page_skins/control_background.jpg']],
  albumFrame:[['قاب مارپیچ','page_frames/frame_cosmic_spiral.png'],['قاب طلایی','page_frames/frame_gold_floral.png']],
  theme:[['ست کریستال','page_frames/frame_rainbow_crystal.png'],['ست طلایی','page_frames/frame_gold_floral.png'],['ست کهکشانی','page_frames/frame_cosmic_spiral.png']]
 },
 effects:['نور آرام','درخشش قلبی','شفق نوا','جرقه خاطره','هاله طلایی','نبض کهکشانی']
};
const family=[
 {label:'زهره',portrait:'secret_room/portrait_zohreh.png',chest:'secret_room/chest_zohreh.png',msg:'زهره جان، حضورت برای این خانه یک نور آرام و دوست‌داشتنی است. همیشه لبخندت را با خودت به خاطره‌های این خانواده بیاور.'},
 {label:'مادر',portrait:'secret_room/portrait_mother.png',chest:'secret_room/chest_mother.png',msg:'عزیزانم، شما برای من فقط اعضای یک خانواده نیستید؛ شما قشنگ‌ترین بخش زندگی من و دلیل خیلی از لبخندهای من هستید.'},
 {label:'حسین',portrait:'secret_room/portrait_hosein.png',chest:'secret_room/chest_hosein.png',msg:'حسین جان، بودنت برای این خانواده یعنی یک تکیه‌گاه، یک لبخند و یک خاطره‌ی خوب که همیشه می‌ماند.'},
 {label:'زینب',portrait:'secret_room/portrait_zeynab.png',chest:'secret_room/chest_zeynab.png',msg:'زینب عزیزم، مهربانی و شیرینی حضورت یکی از رنگ‌های زیبای این خانواده است؛ همیشه خودت باش و بدرخش.'},
 {label:'پدر',portrait:'secret_room/portrait_father.png',chest:'secret_room/chest_father.png',msg:'پدر عزیز، حضور تو بخشی از ستون‌های این خانه و بخشی از خاطراتی است که برای همیشه ارزشمند می‌مانند.'}
];
let secretTaps=0;
let secretState=loadSecretState();
let sharedAuthState=loadSharedAuthState();
let secretGalleryTarget=null;
let webAuthMode='login';
let secretGalleryInput=null;
let secretModalTarget=null;

function img(src,cls=''){return `<img class="${cls}" src="${src?.startsWith('data:')?src:A+src}" alt="">`}
function frame(content,cls=''){screen.innerHTML=`<section class="page ${cls}">${content}</section>`}
function setDock(active){dock.innerHTML=nav.map(([key,file,label])=>`<button class="dock-btn ${active===key?'active':''}" aria-label="${label}" onclick="go('${key}')">${img('nav_main/'+file)}</button>`).join('')}
function go(route){history.replaceState({},'',`#${route}`); render(route)}
function render(route=location.hash.slice(1)||'bluetooth'){
 syncOrientation(route);
 setDock(route.startsWith('rgb')?'rgb':route.startsWith('galaxy')?'galaxy':route);
 const map={bluetooth:bluetooth,usb:usb,music:music,rgb:rgb,galaxy:galaxy,ai:nora,control:control};
 if(route==='secret_room') return secretGate();
 if(route==='secret_settings') return secretSettings();
 if(route==='secret_treasury') return treasury();
 if(route==='secret_family') return familyPage();
 if(route==='secret_album') return albumPage();
 if(route.startsWith('secret_chest_')) return chestDetail(Number(route.split('_').pop()));
 if(route==='rgb_color'||route==='rgb_effects') return rgb(route);
 if(route==='galaxy_color'||route==='galaxy_effects'||route==='galaxy_wheels') return galaxy(route);
 if(route==='equalizer') return equalizer();
 if(route==='control_frames') return subControl('frames');
 if(route==='control_fuses') return subControl('fuses');
 if(route==='sensors') return sensors();
 if(route==='shared_password') return sharedPassword();
 (map[route]||bluetooth)();
}
function syncOrientation(route){const landscape=route==='secret_family';try{if(window.AndroidOrientation){window.AndroidOrientation.setOrientation(landscape?'landscape':'portrait');return}}catch(e){}try{if(screen.orientation?.lock)screen.orientation.lock(landscape?'landscape':'portrait').catch(()=>{})}catch(e){}}
function bluetooth(){frame(`<div class="hero bluetooth-hero"><div class="eyebrow">بلوتوث نوا</div>${img('backgrounds/bluetooth_background_selected_2.jpg','full-bg')}<div class="bt-hands-wrap" id="btHands">${img('page_skins/bt_hands_loose.jpg','hands bt-hands-idle')}${img('page_skins/bt_hands_conn.jpg','hands bt-hands-connected')}<div class="bt-link-beam"></div></div><div class="bt-state" id="btState"><b>آماده برای اتصال</b><small>برای پیوند با کوروش نوا لمس کن</small></div><button class="magic-main bt-connect-btn" onclick="toggleBluetooth(this)">${img('buttons/bluetooth.png')}<span>اتصال به کوروش نوا</span></button><div class="bt-quick-actions"><button class="bt-quick magic-target" onclick="toggleSpeakerWifi(this)">${img('buttons/wifi.svg')}<b>Wi‑Fi</b><small>روشن</small></button><button class="bt-quick magic-target" onclick="toggleSpeakerPower(this)">${img('buttons/power.svg')}<b>اسپیکر</b><small>روشن</small></button></div><div class="status" id="btStatus">دست کوچک آزاد است؛ با لمس، پیوند جادویی برقرار می‌شود.</div></div>`,'bluetooth')}
function toggleSpeakerWifi(btn){const on=!btn.classList.contains('is-on');btn.classList.toggle('is-on',on);btn.querySelector('small').textContent=on?'روشن':'خاموش';btn.setAttribute('aria-label',`Wi‑Fi ${on?'روشن':'خاموش'}`);const s=document.getElementById('btStatus');if(s)s.textContent=on?'Wi‑Fi نوا روشن است.':'Wi‑Fi نوا خاموش است.';magicTouch(btn)}
function toggleSpeakerPower(btn){const on=!btn.classList.contains('is-on');btn.classList.toggle('is-on',on);btn.querySelector('small').textContent=on?'روشن':'خاموش';btn.setAttribute('aria-label',`اسپیکر ${on?'روشن':'خاموش'}`);document.querySelector('.bluetooth-hero')?.classList.toggle('speaker-off',!on);const s=document.getElementById('btStatus');if(s)s.textContent=on?'اسپیکر کوروش نوا روشن است.':'اسپیکر کوروش نوا خاموش شد.';magicTouch(btn)}
function toggleBluetooth(btn){const on=!btn.classList.contains('connected');btn.classList.toggle('connected',on);const hands=document.getElementById('btHands');const state=document.getElementById('btState');const status=document.getElementById('btStatus');hands?.classList.toggle('is-connected',on);state.innerHTML=on?'<b>کوروش نوا متصل شد</b><small>پیوند بلوتوث برقرار است</small>':'<b>آماده برای اتصال</b><small>برای پیوند با کوروش نوا لمس کن</small>';status.textContent=on?'دست کوچک دست بزرگ را گرفته است.':'دست کوچک هنوز آزاد است.';btn.querySelector('span').textContent=on?'قطع اتصال':'اتصال به کوروش نوا';btn.classList.add('bt-pulse');setTimeout(()=>btn.classList.remove('bt-pulse'),420)}
function usb(){frame(`<div class="hero"><div class="eyebrow">گنجینه نوا</div>${img('usb/usb_second_design.png','full-art')}<div class="vertical-volume">−<div></div>+</div><button class="invisible-hotspot" aria-label="پخش USB" onclick="this.classList.toggle('playing')"></button></div>`,'usb')}
function music(){frame(`<div class="hero music-page">${img('music_green_skin.png','full-art')}<div class="record-wrap">${img('music_green_disc2.png','record')}</div><div class="magic-row"><button class="magic-icon">${img('buttons/prev.png')}</button><button class="magic-icon big">${img('buttons/play.png')}</button><button class="magic-icon">${img('buttons/next.png')}</button></div><button class="equalizer-hotspot" onclick="go('equalizer')">${img('buttons/equalizer.png')}</button><button class="secret-hotspot" onclick="secretTap()"></button><div id="secretCounter" class="secret-counter"></div></div>`,'music')}
function secretTap(){secretTaps++;const e=document.querySelector('.music-page');if(e){e.classList.add('flash');setTimeout(()=>e.classList.remove('flash'),220)}if(secretTaps>=5){secretTaps=0;setTimeout(()=>go('secret_room'),280)}}
function rgb(route='rgb'){const pages={rgb:['rgb_custom_page1.png','RGB چهار سیمه','سه کنترل اصلی'],rgb_color:['rgb_custom_page2.png','رنگ دلخواه','چرخه رنگ و شدت'],rgb_effects:['rgb_custom_page3.png','افکت‌های RGB','۲۰ افکت زنده']};const [art,title,sub]=pages[route];frame(`<div class="art-page">${img('page_skins/rgb_background_clean.jpg','bg')}${img(art,'authored-art')}<div class="hotspot-grid">${Array.from({length:route==='rgb_effects'?20:3},(_,i)=>`<button class="hotspot" onclick="pulse(this)">${route==='rgb_effects'?'افکت '+(i+1):i===0?'روشن/خاموش':i===1?'شدت':'رنگ'}</button>`).join('')}</div><div class="page-caption"><b>${title}</b><span>${sub}</span></div></div>`,'art-page-wrap')}
function galaxy(route='galaxy'){const pages={galaxy:['galaxy_ui_galaxy_color_art.png','رنگ کهکشان'],galaxy_color:['galaxy_ui_galaxy_color_art.png','رنگ کهکشان'],galaxy_effects:['galaxy_ui_galaxy_effects_art.png','۳۰ افکت کهکشانی'],galaxy_wheels:['galaxy_ui_galaxy_wheels_art.png','گردون‌های کهکشان']};const [art,title]=pages[route]||pages.galaxy;let controls=route==='galaxy_wheels'?`<div class="wheel-controls"><button class="magic-wheel" onclick="pulse(this)">${img('buttons/wheel_up.png')}<span>گردون بالا</span></button><button class="magic-wheel" onclick="pulse(this)">${img('buttons/wheel_down.png')}<span>گردون پایین</span></button></div>`:`<div class="hotspot-grid">${Array.from({length:route==='galaxy_effects'?30:4},(_,i)=>`<button class="hotspot" onclick="pulse(this)">${route==='galaxy_effects'?'افکت '+(i+1):i===0?'رنگ':'گزینه '+i}</button>`).join('')}</div>`;frame(`<div class="art-page">${img('page_skins/galaxy_background_clean.jpg','bg')}${img(art,'authored-art')}${controls}<div class="page-caption"><b>${title}</b><span>تصویر اختصاصی پروژه + لمس زنده</span></div></div>`,'art-page-wrap')}
function nora(){frame(`<div class="nora-page">${img('backgrounds/ai_family.jpg','bg')}${img('custom_ui/nora_uploaded_skin.gif','nora-skin')}<button class="nora-mic" onclick="pulse(this)">${img('magic_buttons/ai_mic.png')}</button><button class="nora-eq" onclick="go('equalizer')">${img('buttons/equalizer.png')}</button><div class="nora-copy">نورا<br><small>برای تست، میکروفون و مسیر اکولایزر آماده است.</small></div></div>`,'nora')}

/* ===================== ROOM OF COMMAND ===================== */
const controlOptions={
 equalizer:{title:'اکولایزر آوا',image:'equalizer_dj/dj_disc_magenta.png',bg:'equalizer_dj/dj_background.png'},
 frames:{title:'قاب صفحات',image:'page_frames/frame_rainbow_crystal.png',bg:'page_skins/control_background_bright.jpg'},
 fuses:{title:'فیوزهای نوا',image:'control_special/control_fuse_header_icon_v94.png',bg:'page_skins/control_background_bright.jpg'},
 sensors:{title:'حسگرهای نوا',image:'nav_main/control.png',bg:'page_skins/control_background_bright.jpg'}
};
function control(){frame(`<div class="control-page">${img('page_skins/control_background.jpg','bg')}${img('page_frames/frame_cosmic_spiral.png','frame')}<button class="secret-settings-key magic-target" onclick="go('secret_settings')" aria-label="تنظیمات اتاق مخفی"><img src="${A}control_special/control_fuse_header_icon_v94.png" class="key-image"><span class="key-whisper">اگر خاطره‌ای عزیز است، جایش را با مهر پیدا کن… ✨</span></button><div class="control-grid"><button class="magic-target" onclick="go('equalizer')">${img(controlOptions.equalizer.image)}<b>اکولایزر</b><small>تنظیم صدای آوا</small></button><button class="magic-target" onclick="go('control_frames')">${img(controlOptions.frames.image)}<b>قاب صفحات</b><small>انتخاب ظاهر صفحه‌ها</small></button><button class="magic-target" onclick="go('control_fuses')">${img(controlOptions.fuses.image)}<b>فیوزهای نوا</b><small>مدیریت مدارهای حفاظتی</small></button><button class="magic-target" onclick="go('sensors')">${img(controlOptions.sensors.image)}<b>حسگرها</b><small>مدیریت ورودی‌های حسگر</small></button><button class="magic-target" onclick="go('shared_password')">${img('buttons/lock.png')}<b>رمز مشترک</b><small>یک رمز خانوادگی برای همه گوشی‌ها</small></button></div></div>`,'control')}
function controlShell(kind,body){const o=controlOptions[kind];return frame(`<div class="control-detail ${kind}">${img(o.bg,'bg')}${img('page_frames/frame_cosmic_spiral.png','frame')}<div class="control-detail-head">${img(o.image,'control-detail-icon')}<div><h1>${o.title}</h1><p>این بخش صفحه مستقل خودش را دارد و همه انتخاب‌ها با لمس زنده اجرا می‌شوند.</p></div></div>${body}<button class="control-back magic-target" onclick="go('control')">${img('nav_main/control.png')}<b>بازگشت به اتاق فرمان</b></button></div>`,'control-detail-page')}
function equalizer(){return controlShell('equalizer',`<div class="control-option-grid">${['پروفایل آرام','پروفایل مهمانی','پروفایل سینمایی','پروفایل صدای شفاف','پروفایل بیس عمیق'].map((x,i)=>`<button class="control-option magic-target" onclick="selectControlChoice(this,'${x}')">${img(i%2?'equalizer_dj/dj_disc_magenta.png':'buttons/equalizer.png')}<b>${x}</b><span>انتخاب پروفایل</span></button>`).join('')}</div><div id="controlChoice" class="control-choice-result">پروفایل فعلی: آماده انتخاب</div>`)}
function subControl(kind){const items=kind==='frames'?[['قاب کریستال','page_frames/frame_rainbow_crystal.png'],['قاب طلایی','page_frames/frame_gold_floral.png'],['قاب مارپیچ','page_frames/frame_cosmic_spiral.png']]:[['فیوز اصلی','control_special/control_fuse_header_icon_v94.png'],['فیوز نور','control_special/control_fuse_header_icon_v94.png'],['فیوز آمپلی‌فایر','control_special/control_fuse_header_icon_v94.png'],['فیوز USB','control_special/control_fuse_header_icon_v94.png']];return controlShell(kind,`<div class="control-option-grid">${items.map(([x,im])=>`<button class="control-option magic-target" onclick="selectControlChoice(this,'${x}')">${img(im)}<b>${x}</b><span>${kind==='frames'?'انتخاب قاب':'بررسی وضعیت مدار'}</span></button>`).join('')}</div><div id="controlChoice" class="control-choice-result">${kind==='frames'?'یک قاب را انتخاب کن.':'یک مدار را انتخاب کن تا وضعیتش نمایش داده شود.'}</div>`)}
function sensors(){return controlShell('sensors',`<div class="control-option-grid"><button class="control-option magic-target" onclick="selectControlChoice(this,'حسگر لمس')">${img('nav_main/control.png')}<b>حسگر لمس</b><span>ورودی لمسی ESP32</span></button><button class="control-option magic-target" onclick="selectControlChoice(this,'حسگر نور')">${img('galaxy.png')}<b>حسگر نور</b><span>تشخیص شدت نور</span></button><button class="control-option magic-target" onclick="selectControlChoice(this,'حسگر حرکت')">${img('bluetooth.png')}<b>حسگر حرکت</b><span>تشخیص حرکت محیط</span></button></div><div id="controlChoice" class="control-choice-result">یک حسگر را لمس کن تا وضعیتش نمایش داده شود.</div>`)}
function selectControlChoice(el,label){magicTouch(el);document.querySelectorAll('.control-option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');const out=document.getElementById('controlChoice');if(out)out.innerHTML=`${img('buttons/check.svg','choice-check')}<b>انتخاب شد: ${label}</b>`}

/* ===================== SECRET ROOM GATE ===================== */
function secretGate(){frame(`<div class="secret-gate">${img('page_skins/galaxy_background_clean.jpg','bg')}${img('page_frames/frame_rainbow_crystal.png','frame')}<div class="gate-copy"><h1>راز نوا پیدا شد</h1><p>پنج لمس کامل شد ✨</p>${img('buttons/lock.png','lock')}<div class="congrats">تبریک! راه پنهان به اتاق مخفی نوا را پیدا کردی. 💜</div><button class="unlock-button" onclick="unlockSecretRoom(this)">${img('buttons/lock.png')}<span>لمس کن تا قفل با یک حرکت واقعی باز شود</span></button></div></div>`,'secret-gate')}
function unlockSecretRoom(btn){btn.classList.add('unlocking');setTimeout(()=>{btn.classList.add('unlocked');setTimeout(()=>go('secret_treasury'),650)},850)}

/* ===================== SECRET ROOM — 3 PAGES ===================== */
function secretPageShell(page,title,sub,body){return `<div class="secret-room-page ${page}">${img(secretState.background,'bg')}${img(secretState.frame,'frame')}<div class="secret-title"><h1>${title}</h1><span>${sub}</span></div>${body}<div class="secret-tabs"><button class="magic-target ${page==='treasury'?'selected':''}" onclick="go('secret_treasury')">${img('secret_room/chest_family.png')}<span>گنجینه‌ها</span></button><button class="magic-target ${page==='family'?'selected':''}" onclick="go('secret_family')">${img('secret_room/family_selected.jpg')}<span>خاطره خانواده</span></button><button class="magic-target ${page==='album'?'selected':''}" onclick="go('secret_album')">${img('page_frames/frame_gold_floral.png')}<span>آلبوم خاطره</span></button></div></div>`}
function treasury(){const chest=secretState.chest;return frame(secretPageShell('treasury','گنجینه‌های نوا','پنج صندوق برای پنج عزیز؛ و یک صندوق ویژه برای راز راهنما.',`<div class="treasury-grid">${family.map((p,i)=>{const c=secretState.chests?.[i]||{};return `<button class="chest-card magic-target" onclick="openChest(${i})">${img(c.image||p.chest,'chest-art')}${img(p.portrait,'portrait')}<b>${p.label}</b><small>${c.note||'تصویر و یادداشت اختصاصی'}</small></button>`}).join('')}<button class="chest-card special-chest magic-target" onclick="openGuideChest()">${img('secret_room/chest_family.png','chest-art')}<span class="special-mark">✦</span><b>صندوق راز</b><small>راهنمای مسیر پنهان</small></button></div><div class="chest-theme-note">${img(chest,'mini-theme')}<span>ظاهر صندوق‌ها از اتاق تنظیمات قابل تغییر است.</span><button class="magic-target" onclick="go('secret_settings')">${img('buttons/equalizer.png')}<b>تنظیمات گنجینه</b></button></div><div id="chestModal"></div>`),'secret-room')}
function familyPage(){return frame(secretPageShell('family','قاب خانواده','صفحه در حالت افقی؛ عکس اصلی را هر زمان از گالری جایگزین کن.',`<div class="family-stage">${img(secretState.familyPhoto,'family-photo-main')}<div class="family-caption"><strong>یک خانواده، یک خاطره</strong><span>پنج نفر، یک قاب، یک زندگی</span></div><button class="gallery-big magic-target" onclick="openGallery('familyPhoto')">${img('buttons/wheel_up.png')}<span>انتخاب عکس خانواده از گالری</span></button></div>`),'secret-room family-room')}
function albumPage(){return frame(secretPageShell('album','آلبوم خاطره نوا','جایی برای عکس‌هایی که ارزش ماندن دارند.',`<div class="album-stage">${img(secretState.albumBackground,'album-bg')}${img(secretState.albumFrame,'album-frame')}<div class="album-grid">${secretState.albumPhotos.map((p,i)=>`<button class="memory-photo magic-target" onclick="openGallery('albumPhotos',${i})">${img(p,'memory-img')}<span>خاطره ${i+1}</span></button>`).join('')}</div><button class="album-add magic-target" onclick="addAlbumPhoto()">＋ افزودن یک خاطره از گالری</button></div>`),'secret-room album-room')}

function chestDetail(i){const p=family[i];const cfg=secretState.chests?.[i]||{};const image=cfg.image||p.chest;const note=cfg.note||p.msg;return frame(`<div class="chest-detail-page">${img(secretState.background,'bg')}${img(secretState.frame,'frame')}<div class="chest-detail-card">${img(image,'chest-detail-image')}<div class="chest-detail-name">${img(p.portrait,'chest-detail-portrait')}<div><h1>${p.label}</h1><span>خاطره شخصی این صندوق</span></div></div><div class="chest-note">${note}</div><div class="chest-detail-actions"><button class="magic-target" onclick="openChestGallery(${i})">${img('buttons/gallery.svg')}<b>انتخاب تصویر از گالری</b><small>عکس جدید برای همین صندوق</small></button><button class="magic-target" onclick="editChestNote(${i})">${img('buttons/note.svg')}<b>ویرایش یادداشت</b><small>جمله‌ای که داخل صندوق می‌ماند</small></button></div><button class="control-back magic-target" onclick="go('secret_treasury')">${img('nav_main/control.png')}<b>بازگشت به گنجینه‌ها</b></button></div><input id="chestGalleryInput" class="hidden-file" type="file" accept="image/*" onchange="handleChestGallery(event)"><div id="chestEditModal"></div></div>`,'chest-detail')}
function openChest(i){go('secret_chest_'+i)}
function openChestGallery(i){secretGalleryTarget={target:'chest',index:i};document.getElementById('chestGalleryInput')?.click()}
function handleChestGallery(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{secretState.chests=secretState.chests||{};secretState.chests[secretGalleryTarget.index]={...(secretState.chests[secretGalleryTarget.index]||{}),image:reader.result};saveSecretState();const i=secretGalleryTarget.index;secretGalleryTarget=null;render('secret_chest_'+i)};reader.readAsDataURL(file);event.target.value=''}
function editChestNote(i){const p=family[i],cfg=secretState.chests?.[i]||{};document.getElementById('chestEditModal').innerHTML=`<div class="choice-modal"><div class="choice-card"><button class="modal-x magic-target" onclick="closeChestEdit()">${img('buttons/close.svg')}</button><div class="choice-title">یادداشت صندوق ${p.label}</div><p>جمله‌ای بنویس که با لمس این صندوق برای خانواده بماند.</p><textarea id="chestNoteInput" class="auth-input note-input">${cfg.note||p.msg}</textarea><button class="auth-action magic-target" onclick="saveChestNote(${i})">${img('buttons/check.svg')} ذخیره یادداشت</button></div></div>`}
function saveChestNote(i){const value=document.getElementById('chestNoteInput')?.value.trim();if(!value)return;secretState.chests=secretState.chests||{};secretState.chests[i]={...(secretState.chests[i]||{}),note:value};saveSecretState();closeChestEdit();render('secret_chest_'+i)}
function closeChestEdit(){document.getElementById('chestEditModal').innerHTML=''}

/* ===================== SECRET ROOM SETTINGS ===================== */
function secretSettings(){const items=[
 ['chest','secret_room/chest_family.png','ظاهر صندوقچه‌ها','انتخاب از گالری یا گیفت','chest'],
 ['chestMemories','secret_room/chest_zohreh.png','تصویر و یادداشت صندوق‌ها','برای هر صندوق تصویر گالری و جمله اختصاصی','chestMemories'],
 ['effect','buttons/lock.png','افکت صندوقچه','انتخاب یک افکت و نمایش تیک','effect'],
 ['background','page_skins/galaxy_background_clean.jpg','پس‌زمینه اتاق','انتخاب از گالری یا گیفت','background'],
 ['frame','page_frames/frame_gold_floral.png','قاب دور صفحات','انتخاب از گالری یا گیفت','frame'],
 ['familyPhoto','secret_room/family_selected.jpg','قاب عکس خانواده','عکس افقی از گالری یا گیفت','familyPhoto'],
 ['albumBackground','page_skins/galaxy_background_clean.jpg','پوسته آلبوم','انتخاب از گالری یا گیفت','albumBackground'],
 ['albumFrame','page_frames/frame_cosmic_spiral.png','قاب آلبوم','انتخاب از گالری یا گیفت','albumFrame'],
 ['theme','page_frames/frame_rainbow_crystal.png','ست ظاهری','انتخاب از گالری یا گیفت','theme']
 ];
 frame(`<div class="secret-settings-page">${img('page_skins/control_background.jpg','bg')}${img('page_frames/frame_cosmic_spiral.png','frame')}<div class="settings-heading"><div class="settings-seal">✦</div><div><h1>اتاق تنظیمات راز نوا</h1><p>اینجا ظاهر خاطره‌ها را خودت انتخاب می‌کنی؛ با مهر، با سلیقه، با یک لمس.</p></div></div><div class="settings-grid">${items.map(([id,icon,title,sub])=>`<button class="setting-card magic-target" onclick="openSecretSetting('${id}')"><span class="setting-icon"><img src="${A+icon}" alt=""></span><span class="setting-art">${settingPreview(id)}</span><span class="setting-text"><b>${title}</b><small>${sub}</small></span><span class="setting-arrow">›</span></button>`).join('')}</div><button class="settings-return magic-target" onclick="go('secret_treasury')">${img('nav_main/control.png')}<b>بازگشت به اتاق مخفی</b></button><div id="settingsModal"></div><input id="secretGalleryInput" class="hidden-file" type="file" accept="image/*" onchange="handleGallery(event)"></div>`,'secret-settings')}
function settingPreview(id){const map={chest:secretState.chest,effect:'buttons/lock.png',background:secretState.background,frame:secretState.frame,familyPhoto:secretState.familyPhoto,albumBackground:secretState.albumBackground,albumFrame:secretState.albumFrame,theme:'page_frames/frame_cosmic_spiral.png',chestMemories:'secret_room/chest_zohreh.png'};return img(map[id],'setting-preview-img')}
function openSecretSetting(id){secretModalTarget=id;const modal=document.getElementById('settingsModal');if(id==='effect')return openEffectModal();
 if(id==='chestMemories')return go('secret_chest_0');const title={chest:'ظاهر صندوقچه‌ها',background:'پس‌زمینه اتاق',frame:'قاب دور صفحات',familyPhoto:'قاب عکس خانواده',albumBackground:'پوسته آلبوم',albumFrame:'قاب آلبوم',theme:'ست ظاهری',chestMemories:'تصویر و یادداشت صندوق‌ها'}[id];modal.innerHTML=`<div class="choice-modal"><div class="choice-card"><button class="modal-x magic-target" onclick="closeSettingsModal()">${img('buttons/close.svg')}</button><div class="choice-title">${title}</div><p>دو راه داری؛ از گالری خودت انتخاب کن یا یکی از گیفت‌های آماده نوا را بردار.</p><div class="choice-actions"><button class="magic-target" onclick="openGallery('${id}')">${img('buttons/wheel_up.png')}<b>انتخاب از گالری</b><small>عکس خودت</small></button><button class="magic-target" onclick="openGift('${id}')">${img('secret_room/chest_family.png')}<b>انتخاب گیفت</b><small>هدیه‌های نوا</small></button></div></div></div>`}
function openEffectModal(){document.getElementById('settingsModal').innerHTML=`<div class="choice-modal"><div class="choice-card"><button class="modal-x magic-target" onclick="closeSettingsModal()">${img('buttons/close.svg')}</button><div class="choice-title">افکت صندوقچه</div><p>هر افکتی را لمس کنی، تیک همان لحظه روی انتخابت می‌نشیند و پنجره بسته می‌شود.</p><div class="effect-list">${secretConfig.effects.map(e=>`<button class="effect-option magic-target ${secretState.effect===e?'checked':''}" onclick="selectEffect('${e}')">${img('buttons/effect.svg')}<span class="effect-dot">${secretState.effect===e?'✓':'✦'}</span><b>${e}</b></button>`).join('')}</div></div></div>`}
function openGift(id){const gifts=secretConfig.gifts[id]||[];document.getElementById('settingsModal').innerHTML=`<div class="choice-modal"><div class="choice-card"><button class="modal-x magic-target" onclick="closeSettingsModal()">${img('buttons/close.svg')}</button><div class="choice-title">گیفت‌های نوا</div><p>یکی را لمس کن؛ انتخاب با تیک ثبت می‌شود و پنجره خودش بسته خواهد شد.</p><div class="gift-grid">${gifts.map(([name,src])=>`<button class="gift-option magic-target ${secretState[id]===src?'checked':''}" onclick="selectGift('${id}','${encodeURIComponent(src)}')">${img(src)}<span>${name}</span>${secretState[id]===src?'<i>✓</i>':''}</button>`).join('')}</div></div></div>`}
function selectGift(id,encoded){const value=decodeURIComponent(encoded);secretState[id]=value;if(id==='theme')secretState.frame=value;saveSecretState();closeSettingsModal();render('secret_settings')}
function selectEffect(effect){secretState.effect=effect;saveSecretState();closeSettingsModal();render('secret_settings')}
function closeSettingsModal(){const m=document.getElementById('settingsModal');if(m)m.innerHTML='';secretModalTarget=null}
function openGallery(target,index=null){secretGalleryTarget={target,index};const input=document.getElementById('secretGalleryInput');if(input)input.click()}
function handleGallery(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{if(secretGalleryTarget.target==='albumPhotos'){const i=secretGalleryTarget.index;if(i===null||i===undefined)secretState.albumPhotos.push(reader.result);else secretState.albumPhotos[i]=reader.result}else{secretState[secretGalleryTarget.target]=reader.result;if(secretGalleryTarget.target==='theme')secretState.frame=reader.result}saveSecretState();secretGalleryTarget=null;render(location.hash.slice(1)||'secret_settings')};reader.readAsDataURL(file);event.target.value=''}
function addAlbumPhoto(){openGallery('albumPhotos',null)}
function openGuideChest(){document.getElementById('chestModal').innerHTML=`<div class="modal"><div class="modal-card guide-card">${img('secret_room/chest_family.png','modal-chest')}<div class="light-burst"></div><div class="guide-symbol">✦</div><h2>صندوقی که راه را بلد است</h2><div class="message-box">اگر با محبت دنبال خاطره‌ها می‌گردی، <strong>نور کوچکِ بالای اتاق فرمان را لمس کن… ✨</strong></div><button class="close magic-target" onclick="document.getElementById('chestModal').innerHTML=''">${img('buttons/close.svg')}<span>این راز را نگه می‌دارم</span></button></div></div>`}
function revealMessage(i){const p=family[i];document.getElementById('message').innerHTML=`<div class="message-box">${p.msg}<strong>با مهرِ نوا ❤️</strong></div>`}
function pulse(el){magicTouch(el)}

/* ===================== SHARED PASSWORD / BIOMETRIC ===================== */
function loadSharedAuthState(){try{const x=JSON.parse(localStorage.getItem('koroshNovaSharedAuth')||'null');return x||{pinHash:'',members:[{name:'نفر اول',codeHash:''},{name:'نفر دوم',codeHash:''},{name:'نفر سوم',codeHash:''},{name:'نفر چهارم',codeHash:''}],biometric:false,recoveryReady:false}}catch{return {pinHash:'',members:[{name:'نفر اول',codeHash:''},{name:'نفر دوم',codeHash:''},{name:'نفر سوم',codeHash:''},{name:'نفر چهارم',codeHash:''}],biometric:false,recoveryReady:false}}}
function saveSharedAuth(){try{localStorage.setItem('koroshNovaSharedAuth',JSON.stringify(sharedAuthState))}catch(e){console.warn('Shared authentication state could not be persisted',e)}}
async function digestText(value){if(window.crypto?.subtle){const data=new TextEncoder().encode(value);const buf=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}return btoa(unescape(encodeURIComponent(value)))}
function randomRecoveryCode(){return String(Math.floor(100000+Math.random()*900000))}
function sharedPassword(){const configured=!!sharedAuthState.pinHash;frame(`<div class="shared-auth-page">${img('page_skins/control_background.jpg','bg')}${img('page_frames/frame_gold_floral.png','frame')}<div class="auth-hero">${img('buttons/lock.png','auth-hero-image')}<h1>رمز مشترک نوا</h1><p>این یک رمز خانوادگی واحد است؛ برای همه گوشی‌های خانواده یکسان می‌ماند. در این نسخه، برای انتقال امن بین گوشی‌ها «کد خانوادگی» هم دارد.</p></div><div class="auth-cards"><button class="auth-card magic-target" onclick="openSharedLogin()">${img('buttons/lock.png')}<b>ورود با رمز مشترک</b><small>${configured?'رمز خانوادگی فعال است':'رمز خانوادگی هنوز ساخته نشده'}</small></button><button class="auth-card magic-target" onclick="setupSharedPassword()">${img('control_special/control_fuse_header_icon_v94.png')}<b>ساخت / تغییر رمز</b><small>یک رمز واحد برای خانواده</small></button><button class="auth-card magic-target" onclick="startBiometric()">${img('buttons/fingerprint.svg')}<b>ورود با اثر انگشت</b><small>بیومتریک امن دستگاه</small></button><button class="auth-card magic-target" onclick="openRecovery()">${img('buttons/recovery.svg')}<b>بازیابی رمز</b><small>با کد بازیابی خانواده</small></button><button class="auth-card magic-target" onclick="exportFamilyCode()">${img('buttons/share.svg')}<b>ساخت کد خانوادگی</b><small>انتقال همان رمز به گوشی دیگر</small></button><button class="auth-card magic-target" onclick="importFamilyCode()">${img('buttons/import.svg')}<b>ورود کد خانوادگی</b><small>همگام‌سازی رمز موجود</small></button></div><div id="authModal"></div><button class="settings-return magic-target" onclick="go('control')">${img('nav_main/control.png')}<b>بازگشت به اتاق فرمان</b></button></div>`,'shared-auth')}
function authModal(html){const m=document.getElementById('authModal');if(m)m.innerHTML=`<div class="choice-modal"><div class="choice-card auth-modal-card">${html}</div></div>`}
function openSharedLogin(){if(!sharedAuthState.pinHash){setupSharedPassword();return}authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">ورود به اتاق فرمان</div><p>رمز مشترک را وارد کن.</p><input id="sharedPinInput" class="auth-input" type="password" inputmode="numeric" maxlength="12" placeholder="رمز مشترک"><button class="auth-action magic-target" onclick="verifySharedPin()">${img('buttons/lock.png')} ورود</button><div id="authError" class="auth-error"></div>`)}
function setupSharedPassword(){const members=sharedAuthState.members||[];authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">ساخت رمز مشترک</div><p>یک رمز مشترک بساز و برای حداکثر چهار نفر عضو مجاز نام تعیین کن.</p><input id="newSharedPin" class="auth-input" type="password" inputmode="numeric" maxlength="12" placeholder="رمز جدید"><input id="confirmSharedPin" class="auth-input" type="password" inputmode="numeric" maxlength="12" placeholder="تکرار رمز"><div class="member-list">${members.map((m,i)=>`<div class="member-row"><span>${i+1}</span><input id="member${i}" class="auth-input member-input" value="${m.name||''}" maxlength="24" placeholder="نام نفر ${i+1}"></div>`).join('')}</div><button class="auth-action magic-target" onclick="saveSharedPassword()">${img('buttons/lock.png')} ذخیره رمز و اعضا</button><div id="authError" class="auth-error"></div>`)}
async function saveSharedPassword(){const p=document.getElementById('newSharedPin')?.value||'',c=document.getElementById('confirmSharedPin')?.value||'';const err=document.getElementById('authError');if(p.length<4||p!==c){if(err)err.textContent='رمز باید حداقل ۴ رقم/حرف داشته باشد و دو بار یکسان وارد شود.';return}sharedAuthState.pinHash=await digestText(p);sharedAuthState.members=(sharedAuthState.members||[]).map((m,i)=>({...m,name:document.getElementById('member'+i)?.value?.trim()||`نفر ${i+1}`}));sharedAuthState.recoveryReady=true;saveSharedAuth();closeAuthModal();showRecoveryCodes(true)}
async function verifySharedPin(){const p=document.getElementById('sharedPinInput')?.value||'';const err=document.getElementById('authError');if(await digestText(p)===sharedAuthState.pinHash){closeAuthModal();unlockSharedArea()}else if(err)err.textContent='رمز درست نیست. اگر فراموش شده، از «بازیابی رمز» استفاده کن.'}
function unlockSharedArea(){const el=document.querySelector('.shared-auth-page');if(el){el.classList.add('auth-unlocked');setTimeout(()=>el.classList.remove('auth-unlocked'),850)}}
async function showRecoveryCodes(first=false){const members=sharedAuthState.members||[];let rows='';for(let i=0;i<members.length;i++){const code=randomRecoveryCode();members[i].codeHash=await digestText(code);rows+=`<div class="recovery-row"><b>${members[i].name||`نفر ${i+1}`}</b><strong>${code}</strong><small>این کد را همان نفر نگه دارد؛ فقط برای بازیابی رمز است.</small></div>`}saveSharedAuth();authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">کدهای بازیابی</div><p>${first?'این کدها فقط یک‌بار به تو نشان داده می‌شوند. آن‌ها را برای چهار نفر نگه دار.':'برای هر عضو یک کد بازیابی مستقل ساخته شده است.'}</p><div class="recovery-list">${rows}</div><button class="auth-action magic-target" onclick="closeAuthModal()">${img('buttons/check.svg')} متوجه شدم</button>`)}
function openRecovery(){authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">بازیابی رمز مشترک</div><p>کد بازیابی یکی از چهار نفر را وارد کن؛ بعد رمز مشترک را دوباره تعیین می‌کنیم.</p><input id="recoveryCode" class="auth-input" inputmode="numeric" maxlength="6" placeholder="کد ۶ رقمی"><button class="auth-action magic-target" onclick="verifyRecovery()">${img('buttons/wheel_up.png')} ادامه</button><button class="auth-secondary magic-target" onclick="startBiometric('recovery')">${img('magic_buttons/ai_mic.png')} بازیابی با احراز هویت گوشی</button><div id="authError" class="auth-error"></div>`)}
async function verifyRecovery(){const code=document.getElementById('recoveryCode')?.value||'';let ok=false;for(const m of (sharedAuthState.members||[])){if(m.codeHash&&await digestText(code)===m.codeHash){ok=true;break}}if(ok){closeAuthModal();setTimeout(()=>setupSharedPassword(),50)}else{const e=document.getElementById('authError');if(e)e.textContent='این کد بازیابی معتبر نیست.'}}

function familyPayload(){return {version:1,pinHash:sharedAuthState.pinHash,members:(sharedAuthState.members||[]).map(m=>({name:m.name||'',codeHash:m.codeHash||''}))}}
function exportFamilyCode(){if(!sharedAuthState.pinHash){setupSharedPassword();return}const raw=JSON.stringify(familyPayload());const code=btoa(unescape(encodeURIComponent(raw)));authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">کد خانوادگی نوا</div><p>این کد همان رمز مشترک را به گوشی دیگر منتقل می‌کند؛ آن را فقط با اعضای خانواده به اشتراک بگذار.</p><textarea class="auth-input family-code" readonly>${code}</textarea><button class="auth-action magic-target" onclick="copyFamilyCode()">${img('buttons/share.svg')} کپی کد</button><div id="copyStatus" class="auth-error"></div>`)}
async function copyFamilyCode(){const t=document.querySelector('.family-code')?.value||'';try{await navigator.clipboard.writeText(t);document.getElementById('copyStatus').textContent='کد کپی شد؛ آن را روی گوشی خانواده وارد کن.'}catch{document.querySelector('.family-code')?.select();document.getElementById('copyStatus').textContent='کد انتخاب شد؛ کپی کن و به گوشی دیگر منتقل کن.'}}
function importFamilyCode(){authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">ورود کد خانوادگی</div><p>کد خانوادگی را از گوشیِ صاحب رمز بگیر و اینجا وارد کن.</p><textarea id="familyCodeInput" class="auth-input family-code" placeholder="کد خانوادگی"></textarea><button class="auth-action magic-target" onclick="applyFamilyCode()">${img('buttons/check.svg')} همگام‌سازی رمز</button><div id="authError" class="auth-error"></div>`)}
function applyFamilyCode(){try{const raw=decodeURIComponent(escape(atob(document.getElementById('familyCodeInput')?.value.trim()||'')));const data=JSON.parse(raw);if(!data.pinHash)throw new Error();sharedAuthState={...sharedAuthState,pinHash:data.pinHash,members:Array.isArray(data.members)?data.members.slice(0,4):sharedAuthState.members,recoveryReady:true};saveSharedAuth();closeAuthModal();render('shared_password')}catch{const e=document.getElementById('authError');if(e)e.textContent='کد خانوادگی معتبر نیست.'}}
async function startBiometric(mode='login'){webAuthMode=mode;if(window.AndroidAuth?.authenticate){window.AndroidAuth.authenticate();return}if(!window.isSecureContext||!window.PublicKeyCredential){authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">اثر انگشت / Passkey</div><p>مرورگر فقط در محیط امن HTTPS و با پشتیبانی WebAuthn می‌تواند از حسگر امن گوشی استفاده کند.</p><button class="auth-action magic-target" onclick="closeAuthModal()">${img('buttons/check.svg')} متوجه شدم</button>`);return}try{const stored=JSON.parse(localStorage.getItem('koroshNovaWebAuth')||'null');if(stored?.credentialId&&stored?.publicKey){await webAuthAuthenticate(stored);return}await webAuthRegister();}catch(e){authModal(`<button class="modal-x magic-target" onclick="closeAuthModal()">${img('buttons/close.svg')}</button><div class="choice-title">حسگر امن در دسترس نیست</div><p>اگر مرورگر یا دستگاه اجازه نداد، از رمز مشترک یا کد بازیابی استفاده کن.</p><button class="auth-action magic-target" onclick="closeAuthModal()">${img('buttons/check.svg')} باشه</button>`)}}
function b64url(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function randomBytes(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
async function webAuthRegister(){const challenge=randomBytes(32);const userId=randomBytes(16);const cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'کوروش نوا',id:location.hostname},user:{id:userId,name:'korosh-nova',displayName:'کوروش نوا'},pubKeyCredParams:[{type:'public-key',alg:-7}],authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},timeout:60000,attestation:'none'}});const pk=cred?.response?.getPublicKey?.();if(!cred||!pk)throw new Error('public key unavailable');localStorage.setItem('koroshNovaWebAuth',JSON.stringify({credentialId:b64url(cred.rawId),publicKey:b64url(pk)}));biometricResult(true)}
async function webAuthAuthenticate(stored){const challenge=randomBytes(32);const cred=await navigator.credentials.get({publicKey:{challenge,allowCredentials:[{type:'public-key',id:fromB64url(stored.credentialId)}],userVerification:'required',timeout:60000}});if(!cred)throw new Error('no credential');const r=cred.response;const clientHash=await crypto.subtle.digest('SHA-256',r.clientDataJSON);const signed=new Uint8Array(r.authenticatorData.byteLength+clientHash.byteLength);signed.set(new Uint8Array(r.authenticatorData),0);signed.set(new Uint8Array(clientHash),r.authenticatorData.byteLength);const key=await crypto.subtle.importKey('spki',fromB64url(stored.publicKey),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);const ok=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,r.signature,signed);if(!ok)throw new Error('signature invalid');const flags=new Uint8Array(r.authenticatorData)[32];if((flags&4)!==4)throw new Error('user verification missing');biometricResult(true)}
function biometricResult(ok){if(ok){closeAuthModal();if(webAuthMode==='recovery'){setTimeout(()=>setupSharedPassword(),60)}else unlockSharedArea()}else{const e=document.getElementById('authError');if(e)e.textContent='احراز هویت انجام نشد؛ می‌توانی با رمز مشترک یا کد بازیابی ادامه بدهی.'}}
function closeAuthModal(){const m=document.getElementById('authModal');if(m)m.innerHTML=''}

/* ===================== MAGIC TOUCH ENGINE ===================== */
function magicTouch(el){if(!el)return;el.classList.remove('magic-pressed');void el.offsetWidth;el.classList.add('magic-pressed');setTimeout(()=>el.classList.remove('magic-pressed'),420)}
function emitMagicTouch(x,y){const layer=document.createElement('div');layer.className='touch-magic-layer';layer.style.left=x+'px';layer.style.top=y+'px';layer.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i><b></b>';document.body.appendChild(layer);setTimeout(()=>layer.remove(),560)}
document.addEventListener('pointerdown',e=>{const target=e.target.closest('button,a,input,select,[role="button"]');if(!target)return;emitMagicTouch(e.clientX,e.clientY);magicTouch(target)},{passive:true});
function loadSecretState(){try{const saved=JSON.parse(localStorage.getItem('koroshNovaSecretRoom')||'null');return {...secretConfig.defaults,chests:{},albumPhotos:['secret_room/family_selected.jpg','secret_room/portrait_mother.png','secret_room/portrait_father.png'],...(saved||{})}}catch{return {...secretConfig.defaults,chests:{},albumPhotos:['secret_room/family_selected.jpg','secret_room/portrait_mother.png','secret_room/portrait_father.png']}}}
function saveSecretState(){try{localStorage.setItem('koroshNovaSecretRoom',JSON.stringify(secretState))}catch(e){console.warn('Secret room settings could not be persisted',e)}}

window.addEventListener('hashchange',()=>render());
if(location.hash==='#control_frames')subControl('frames'); else if(location.hash==='#control_fuses')subControl('fuses'); else if(location.hash==='#equalizer')equalizer(); else render();
